export default [
  {
    name: 'John Doe',
    username: 'johndoe',
    userColor: '#5c36ba',
    userId: 12345,
    email: 'johndoe@peopledatalabs.com',
    avatar: 'https://i.pravatar.cc/300',
    bio: 'I am a software engineer',
    location: 'San Francisco, CA',
    website: 'https://www.peopledatalabs.com',
    social: {
      github: 'https://github.com/peopledatalabs',
      twitter: 'https://twitter.com/peopledatalabs',
      linkedin: 'https://www.linkedin.com/company/peopledatalabs',
      facebook: 'https://www.facebook.com/peopledatalabs',
      instagram: 'https://www.instagram.com/peopledatalabs',
    },
    createdAt: '2020-01-01T00:00:00.000Z',
    updatedAt: '2020-01-01T00:00:00.000Z',
  },
  {
    name: 'Jane Doe',
    username: 'janedoe',
    userColor: '#5c36ba',
    userId: 678910,
    email: 'janedoe@peopledatalabs.com',
    avatar: 'https://i.pravatar.cc/300',
    bio: 'I am a API developer',
    location: 'Miami, FL',
    website: 'https://www.peopledatalabs.com',
    social: {
      github: 'https://github.com/peopledatalabs',
      twitter: 'https://twitter.com/peopledatalabs',
      linkedin: 'https://www.linkedin.com/company/peopledatalabs',
      facebook: 'https://www.facebook.com/peopledatalabs',
      instagram: 'https://www.instagram.com/peopledatalabs',
    },
    createdAt: '2020-01-01T00:00:00.000Z',
    updatedAt: '2020-01-01T00:00:00.000Z',
  },
  {
    name: 'Jacob Doe',
    username: 'jacobdoe',
    userColor: 'hsl(36,100%,50%)',
    userId: 111213,
    email: 'jacobdoe@peopledatalabs.com',
    avatar: 'https://i.pravatar.cc/300',
    bio: 'I am a backend engineer',
    location: 'San Francisco, CA',
    website: 'https://www.peopledatalabs.com',
    social: {
      github: 'https://github.com/peopledatalabs',
      twitter: 'https://twitter.com/peopledatalabs',
      linkedin: 'https://www.linkedin.com/company/peopledatalabs',
      facebook: 'https://www.facebook.com/peopledatalabs',
      instagram: 'https://www.instagram.com/peopledatalabs',
    },
    createdAt: '2020-01-01T00:00:00.000Z',
    updatedAt: '2020-01-01T00:00:00.000Z',
  },
  {
    name: 'Jason Doe',
    username: 'jasondoe',
    userColor: 'red',
    userId: 141516,
    email: 'johndoe@peopledatalabs.com',
    avatar: 'https://i.pravatar.cc/300',
    bio: 'I am a data engineer',
    location: 'New York, NY',
    website: 'https://www.peopledatalabs.com',
    social: {
      github: 'https://github.com/peopledatalabs',
      twitter: 'https://twitter.com/peopledatalabs',
      linkedin: 'https://www.linkedin.com/company/peopledatalabs',
      facebook: 'https://www.facebook.com/peopledatalabs',
      instagram: 'https://www.instagram.com/peopledatalabs',
    },
    createdAt: '2020-01-01T00:00:00.000Z',
    updatedAt: '2020-01-01T00:00:00.000Z',
  },
  {
    name: 'Alex Doe',
    username: 'alexdoe',
    userColor: 'yellow',
    userId: 171819,
    email: 'alexdoe@peopledatalabs.com',
    avatar: 'https://i.pravatar.cc/300',
    bio: 'I am a ux/ui designer :)',
    location: 'Scottsdale, AZ',
    website: 'https://www.peopledatalabs.com',
    social: {
      github: 'https://github.com/peopledatalabs',
      twitter: 'https://twitter.com/peopledatalabs',
      linkedin: 'https://www.linkedin.com/company/peopledatalabs',
      facebook: 'https://www.facebook.com/peopledatalabs',
      instagram: 'https://www.instagram.com/peopledatalabs',
    },
    createdAt: '2020-01-01T00:00:00.000Z',
    updatedAt: '2020-01-01T00:00:00.000Z',
  },
];
